doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '8.0.31'
    types:
      json: Doctrine\DBAL\Types\JsonType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    controller_resolver:
      auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
