security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\AdminUser:
      algorithm: auto
    App\Entity\User:
      algorithm: auto

  providers:
    app_admin_provider:
      entity:
        class: App\Entity\AdminUser
        property: email
    app_user_provider:
      id: App\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_user_login
        check_path: app_user_login
        enable_csrf: false
        username_parameter: login[email]
        password_parameter: login[password]
        success_handler: App\Security\AuthenticationSuccessHandler
      logout:
        path: /user/logout
        target: app_article_index
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 1 week in seconds
        path: /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/articles/new, roles: ROLE_ADMIN }
    - { path: ^/articles/\d+/edit, roles: ROLE_ADMIN }
    - { path: ^/articles/\d+/delete, roles: ROLE_ADMIN }
    - { path: ^/categories/new, roles: ROLE_ADMIN }
    - { path: ^/categories/\d+/edit, roles: ROLE_ADMIN }
    - { path: ^/categories/\d+/delete, roles: ROLE_ADMIN }
    - { path: ^/comments/\d+/delete, roles: ROLE_ADMIN }
    - { path: ^/comments/new, roles: ROLE_USER }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/register, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
