security:
  password_hashers:
    App\Entity\AdminUser:
      algorithm: auto

  providers:
    admin_user_provider:
      entity:
        class: App\Entity\AdminUser
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: admin_user_provider
      custom_authenticator:
        - App\Security\AdminAuthenticator
      entry_point: App\Security\AdminAuthenticator
      logout:
        path: logout
        target: /
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
